
<form method="post">
    
    <label for ="usuario">Usuario</label><br/>
    <input type="text" name="usuario" value="<?php echo $this->usuario ?>" placeholder="Usuario" />
    <br/>
    
    <label for ="password">Contraseña</label><br/>
    <input type="password" name="password" placeholder="Introduzca su Contraseña"/>
    <br/>
       
    <input type="submit" value="Acceder">
    </form>

<?php $this->placeholder('texto_blanco')->captureStart()?>
    <?php echo $this->form ?>
<?php $this->placeholder('texto_blanco')->captureEnd()?>
    

<h3>
<?php echo $this->error ?>
</h3>